// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk80W3XKYs9veJ-cvQxtNCxY6bP4Gm2h4',
    appId: '1:251883230030:web:20ca1a04a552cd2658441f',
    messagingSenderId: '251883230030',
    projectId: 'mobile-project-4d658',
    authDomain: 'mobile-project-4d658.firebaseapp.com',
    storageBucket: 'mobile-project-4d658.firebasestorage.app',
    measurementId: 'G-9JK8Y7R7YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM5imsCueW5g6oDoExF-yg4G3MKNyXk-E',
    appId: '1:251883230030:android:216e9cd51094740658441f',
    messagingSenderId: '251883230030',
    projectId: 'mobile-project-4d658',
    storageBucket: 'mobile-project-4d658.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaX4izoyjod81rn1s6wi47OvflnXnW4eo',
    appId: '1:251883230030:ios:b2816b692ccfbad258441f',
    messagingSenderId: '251883230030',
    projectId: 'mobile-project-4d658',
    storageBucket: 'mobile-project-4d658.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaX4izoyjod81rn1s6wi47OvflnXnW4eo',
    appId: '1:251883230030:ios:b2816b692ccfbad258441f',
    messagingSenderId: '251883230030',
    projectId: 'mobile-project-4d658',
    storageBucket: 'mobile-project-4d658.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk80W3XKYs9veJ-cvQxtNCxY6bP4Gm2h4',
    appId: '1:251883230030:web:8196a50b43735c7858441f',
    messagingSenderId: '251883230030',
    projectId: 'mobile-project-4d658',
    authDomain: 'mobile-project-4d658.firebaseapp.com',
    storageBucket: 'mobile-project-4d658.firebasestorage.app',
    measurementId: 'G-WLV2JQFG21',
  );
}
